Repository languitar/autosuspend, pull requests merged in 2020-01, with the labels that each got.

#72 Fix IdleHint checking in LogindSessionsIdle
  .github/workflows/ci.yml
  setup.py
  src/autosuspend/checks/activity.py
  src/autosuspend/util/systemd.py
  tests/conftest.py
  tests/test_checks_activity.py
  tests/test_util_systemd.py
Labels: bug

#66 systemd callback for suspend scheduling
  data/autosuspend-detect-suspend.service
  data/autosuspend.conf
  data/autosuspend.service
  doc/source/changelog.rst
  doc/source/configuration_file.inc
  doc/source/debugging.rst
  doc/source/man_command.rst
  doc/source/systemd_integration.rst
  setup.py
  src/autosuspend/__init__.py
  tests/data/mindeps-test.conf
  tests/test_autosuspend.py
  tests/test_integration.py
  tests/test_integration/dont_suspend.conf
  tests/test_integration/notify.conf
  tests/test_integration/notify_wakeup.conf
  tests/test_integration/temporary_error.conf
  tests/test_integration/would_schedule.conf
  tests/test_integration/would_suspend.conf
  tox.ini
Labels: breaking change, enhancement, new feature

#75 autosuspend in in Debian (stable)
  doc/source/installation.rst
Labels: enhancement
